In [1]:
#!/bin/python
import numpy as np
from sklearn.metrics import mean_squared_error

In [2]:
# User class stores the names and average rating for each user
class User:
    def __init__(self, name, user_id):
        self.name = name
        self.id = user_id
        self.avg_r = 0.0

In [3]:
# Item class stores the name of each item
class Item:
    def __init__(self, name, item_id):
        self.name = name
        self.id = item_id

In [4]:
# Rating class is used to assign ratings
class Rating:
    def __init__(self, user_id, item_id, rating):
        self.user_id = user_id
        self.item_id = item_id
        self.rating = rating

In [5]:
# We store users in a list. Note that user IDs start indexed at 1.
user = []
user.append(User("Ann", 1))
user.append(User("Bob", 2))
user.append(User("Carl", 3))
user.append(User("Doug", 4))

In [6]:
# Items are also stored in a list. Note that item IDs start indexed at 1.
item = []
item.append(Item("HP1", 1))
item.append(Item("HP2", 2))
item.append(Item("HP3", 3))
item.append(Item("SW1", 4))
item.append(Item("SW2", 5))
item.append(Item("SW3", 6))

In [9]:
rating = []
rating.append(Rating(1, 1, 4))
rating.append(Rating(1, 4, 1))
rating.append(Rating(2, 1, 5))
rating.append(Rating(2, 2, 5))
rating.append(Rating(2, 3, 4))
rating.append(Rating(3, 4, 4))
rating.append(Rating(3, 5, 5))
rating.append(Rating(4, 2, 3))
rating.append(Rating(4, 6, 3))

In [10]:
n_users = len(user)
n_items = len(item)
n_ratings = len(rating)

In [11]:
[n_users, n_items, n_ratings]

[4, 6, 9]

In [12]:
# The utility matrix stores the rating for each user-item pair in the matrix form.
utility = np.zeros((n_users, n_items))
for r in rating:
    utility[r.user_id-1][r.item_id-1] = r.rating

In [13]:
utility.shape

(4L, 6L)

In [14]:
print utility

[[ 4.  0.  0.  1.  0.  0.]
 [ 5.  5.  4.  0.  0.  0.]
 [ 0.  0.  0.  4.  5.  0.]
 [ 0.  3.  0.  0.  0.  3.]]


In [16]:
utility.dtype

dtype('float64')